spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
name = "key-value-example"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "key-value"

[component.key-value]
source = "main.wasm"
key_value_stores = ["default"]
[component.key-value.build]
command = "tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm ."
