spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple Spin application written in (Tiny)Go."
name = "hello-example"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello"

[component.hello]
source = "main.wasm"
[component.hello.build]
command = "tinygo build -target=wasip2 --wit-package $(go list -mod=readonly -m -f '{{.Dir}}' github.com/fermyon/spin-go-sdk)/wit --wit-world http-trigger -gc=leaking -no-debug -o main.wasm main.go"
